"""Initial schema: places, user_profiles, user_favorites

Revision ID: c4f12f2086cb
Revises: 
Create Date: 2026-09-20 16:03:29.959578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4f12f2086cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass
    op.add_column('places', sa.Column('place_type', sa.String(length=64), nullable=True))
    op.add_column('places', sa.Column('promo_text', sa.Text(), nullable=True))
    op.add_column('places', sa.Column('schedule', sa.String(length=255), nullable=True))
    op.add_column('places', sa.Column('address', sa.String(length=255), nullable=True))
    op.alter_column('places', 'map_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=True)
    op.create_index(op.f('ix_places_category'), 'places', ['category'], unique=False)
    op.create_index(op.f('ix_places_city'), 'places', ['city'], unique=False)
    op.drop_column('places', 'description')
    op.alter_column('user_favorites', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_favorites', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('user_profiles', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_column('user_profiles', 'created_at')
    op.drop_constraint(None, 'user_favorites', type_='foreignkey')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.alter_column('user_favorites', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('places', sa.Column('description', mysql.TEXT(), nullable=False))
    op.drop_index(op.f('ix_places_city'), table_name='places')
    op.drop_index(op.f('ix_places_category'), table_name='places')
    op.alter_column('places', 'map_url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('places', 'address')
    op.drop_column('places', 'schedule')
    op.drop_column('places', 'promo_text')
    op.drop_column('places', 'place_type')
    op.create_table('user_activity_log',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payload', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_states',
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
